name: Build and Deploy

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - '../../docs-github/**'
      - '.github/**'
      - '!.github/workflows/build.yml'
  push:
    branches:
      - main
    tags: '[0-9]+.[0-9]+.[0-9]+'
    paths-ignore:
      - 'README.md'
      - '../../docs-github/**'
      - '.github/**'
      - '!.github/workflows/build.yml'
  release:
    types:
      - created

jobs:
  build:
    strategy:
      matrix:
        service: [ client, server ]
    uses: ls1intum/.github/.github/workflows/build-and-push-docker-image.yml@main
    with:
      image-name: ghcr.io/ls1intum/staffplan-${{ matrix.service }}
      docker-file: docker/${{ matrix.service }}.Dockerfile
    secrets: inherit

  deploy-staging:
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: ls1intum/.github/.github/workflows/deploy-docker-compose.yml@main
    with:
      environment: staging
      docker-compose-file: './docker/docker-compose-prod.yml'
      main-image-name: ghcr.io/ls1intum/staffplan-server
      image-tag: latest
      deployment-base-path: '/opt/staffplan'
    secrets: inherit

  deploy-production:
    needs: deploy-staging
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: ls1intum/.github/.github/workflows/deploy-docker-compose.yml@main
    with:
      environment: production
      docker-compose-file: './docker/docker-compose-prod.yml'
      main-image-name: ghcr.io/ls1intum/staffplan-server
      image-tag: latest
      deployment-base-path: '/opt/staffplan'
    secrets: inherit
